name: download-artifact

description: Download Artifact

inputs:
  platform:
    description: Platform
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.platform }}.env
        path: ${{ inputs.platform }}.env
    - name: Env to output
      shell: bash
      run: |
        sed -i 's/\r//g' ${{ inputs.platform }}.env/sorac.env
        source ${{ inputs.platform }}.env/sorac.env
        echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "sumomo_package_name=$sumomo_PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "$PACKAGE_NAME/$PACKAGE_NAME" >> package_paths.env
        echo "$SUMOMO_PACKAGE_NAME/$SUMOMO_PACKAGE_NAME" >> package_paths.env
      id: env
    - uses: actions/download-artifact@v3
      with:
        name: ${{ steps.env.outputs.package_name }}
        path: ${{ steps.env.outputs.package_name }}
    - uses: actions/download-artifact@v3
      with:
        name: ${{ steps.env.outputs.sumomo_package_name }}
        path: ${{ steps.env.outputs.sumomo_package_name }}
